<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_ical"
 *
 * Auto generated by Extension Builder 2017-05-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'iCal',
    'description' => 'Provides classes to render ical via eluceo iCal lib (https://github.com/markuspoerschke/iCal)',
    'category' => 'plugin',
    'author' => 'André Wuttig',
    'author_email' => 'wuttig@portrino.de',
    'author_company' => 'portrino GmbH',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.2.1',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.18-7.99.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ]
];
